<?php
return [
    'ctrl' => [
        'title' => 'Waehrung',
        'label' => 'uid',
        'tstamp' => 'tstamp',
        'crdate' => 'crdate',
        'cruser_id' => 'cruser_id',
        'versioningWS' => true,
        'languageField' => 'sys_language_uid',
        'transOrigPointerField' => 'l10n_parent',
        'transOrigDiffSourceField' => 'l10n_diffsource',
        'delete' => 'deleted',
        'enablecolumns' => [
            'disabled' => 'hidden',
            'starttime' => 'starttime',
            'endtime' => 'endtime',
        ],
        'searchFields' => 'iso_waehrung',
        'iconfile' => 'EXT:core/Resources/Public/Icons/T3Icons/information/information-typo3-version.svg'
    ],
    'interface' => [
        'showRecordFieldList' => 'sys_language_uid, l10n_parent, l10n_diffsource, hidden, iso_waehrung',
    ],
    'types' => [
        '1' => ['showitem' => 'sys_language_uid, l10n_parent, l10n_diffsource, hidden, iso_waehrung, --div--;LLL:EXT:frontend/Resources/Private/Language/locallang_ttc.xlf:tabs.access, starttime, endtime'],
    ],
    'columns' => [
        'sys_language_uid' => [
            'exclude' => true,
            'label' => 'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.language',
            'config' => [
                'type' => 'select',
                'renderType' => 'selectSingle',
                'special' => 'languages',
                'items' => [
                    [
                        'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.allLanguages',
                        -1,
                        'flags-multiple'
                    ]
                ],
                'default' => 0,
            ],
        ],
        'l10n_parent' => [
            'displayCond' => 'FIELD:sys_language_uid:>:0',
            'exclude' => true,
            'label' => 'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.l18n_parent',
            'config' => [
                'type' => 'select',
                'renderType' => 'selectSingle',
                'default' => 0,
                'items' => [
                    ['', 0],
                ],
                'foreign_table' => 'tx_openimmotypo3_domain_model_waehrung',
                'foreign_table_where' => 'AND {#tx_openimmotypo3_domain_model_waehrung}.{#pid}=###CURRENT_PID### AND {#tx_openimmotypo3_domain_model_waehrung}.{#sys_language_uid} IN (-1,0)',
            ],
        ],
        'l10n_diffsource' => [
            'config' => [
                'type' => 'passthrough',
            ],
        ],
        't3ver_label' => [
            'label' => 'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.versionLabel',
            'config' => [
                'type' => 'input',
                'size' => 30,
                'max' => 255,
            ],
        ],
        'hidden' => [
            'exclude' => true,
            'label' => 'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.visible',
            'config' => [
                'type' => 'check',
                'renderType' => 'checkboxToggle',
                'items' => [
                    [
                        0 => '',
                        1 => '',
                        'invertStateDisplay' => true
                    ]
                ],
            ],
        ],
        'starttime' => [
            'exclude' => true,
            'label' => 'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.starttime',
            'config' => [
                'type' => 'input',
                'renderType' => 'inputDateTime',
                'eval' => 'datetime,int',
                'default' => 0,
                'behaviour' => [
                    'allowLanguageSynchronization' => true
                ]
            ],
        ],
        'endtime' => [
            'exclude' => true,
            'label' => 'LLL:EXT:core/Resources/Private/Language/locallang_general.xlf:LGL.endtime',
            'config' => [
                'type' => 'input',
                'renderType' => 'inputDateTime',
                'eval' => 'datetime,int',
                'default' => 0,
                'range' => [
                    'upper' => mktime(0, 0, 0, 1, 1, 2038)
                ],
                'behaviour' => [
                    'allowLanguageSynchronization' => true
                ]
            ],
        ],
        'iso_waehrung' => [
            'exclude' => true,
            'label' => 'IsoWaehrung',
            'config' => [
                'type' => 'select',
                'renderType' => 'selectSingle',
                'default' => 0,
                'items' => [
                    ['', 0],
                    ['Aed', 'AED'],
                    ['Afa', 'AFA'],
                    ['All', 'ALL'],
                    ['Amd', 'AMD'],
                    ['Ang', 'ANG'],
                    ['Aon', 'AON'],
                    ['Arp', 'ARP'],
                    ['Ats', 'ATS'],
                    ['Aud', 'AUD'],
                    ['Awf', 'AWF'],
                    ['Azm', 'AZM'],
                    ['Bak', 'BAK'],
                    ['Bbd', 'BBD'],
                    ['Bdt', 'BDT'],
                    ['Bef', 'BEF'],
                    ['Bes', 'BES'],
                    ['Bgl', 'BGL'],
                    ['Bhd', 'BHD'],
                    ['Bif', 'BIF'],
                    ['Bmd', 'BMD'],
                    ['Bnd', 'BND'],
                    ['Bob', 'BOB'],
                    ['Brl', 'BRL'],
                    ['Bsd', 'BSD'],
                    ['Btr', 'BTR'],
                    ['Bwp', 'BWP'],
                    ['Byr', 'BYR'],
                    ['Bzd', 'BZD'],
                    ['Cad', 'CAD'],
                    ['Cdf', 'CDF'],
                    ['Chf', 'CHF'],
                    ['Clp', 'CLP'],
                    ['Cny', 'CNY'],
                    ['Cop', 'COP'],
                    ['Crc', 'CRC'],
                    ['Cup', 'CUP'],
                    ['Cuw', 'CUW'],
                    ['Cve', 'CVE'],
                    ['Cyp', 'CYP'],
                    ['Czk', 'CZK'],
                    ['Dem', 'DEM'],
                    ['Djf', 'DJF'],
                    ['Dkk', 'DKK'],
                    ['Dop', 'DOP'],
                    ['Dzd', 'DZD'],
                    ['Ecs', 'ECS'],
                    ['Eek', 'EEK'],
                    ['Egp', 'EGP'],
                    ['Ern', 'ERN'],
                    ['Esp', 'ESP'],
                    ['Etb', 'ETB'],
                    ['Eur', 'EUR'],
                    ['Fim', 'FIM'],
                    ['Fjd', 'FJD'],
                    ['Fkp', 'FKP'],
                    ['Frf', 'FRF'],
                    ['Gbp', 'GBP'],
                    ['Gel', 'GEL'],
                    ['Ghc', 'GHC'],
                    ['Gip', 'GIP'],
                    ['Gmd', 'GMD'],
                    ['Gnf', 'GNF'],
                    ['Grd', 'GRD'],
                    ['Gtq', 'GTQ'],
                    ['Gyd', 'GYD'],
                    ['Hkd', 'HKD'],
                    ['Hnl', 'HNL'],
                    ['Hrk', 'HRK'],
                    ['Htg', 'HTG'],
                    ['Huf', 'HUF'],
                    ['Idr', 'IDR'],
                    ['Iep', 'IEP'],
                    ['Ils', 'ILS'],
                    ['Inr', 'INR'],
                    ['Iqd', 'IQD'],
                    ['Irr', 'IRR'],
                    ['Isk', 'ISK'],
                    ['Itl', 'ITL'],
                    ['Jmd', 'JMD'],
                    ['Jod', 'JOD'],
                    ['Jpy', 'JPY'],
                    ['Kes', 'KES'],
                    ['Kgs', 'KGS'],
                    ['Khr', 'KHR'],
                    ['Kmf', 'KMF'],
                    ['Kpw', 'KPW'],
                    ['Krw', 'KRW'],
                    ['Kwd', 'KWD'],
                    ['Kyd', 'KYD'],
                    ['Kzt', 'KZT'],
                    ['Lak', 'LAK'],
                    ['Lbp', 'LBP'],
                    ['Lkr', 'LKR'],
                    ['Lrd', 'LRD'],
                    ['Lsl', 'LSL'],
                    ['Ltl', 'LTL'],
                    ['Luf', 'LUF'],
                    ['Lvl', 'LVL'],
                    ['Lyd', 'LYD'],
                    ['Mad', 'MAD'],
                    ['Mdl', 'MDL'],
                    ['Mgf', 'MGF'],
                    ['Mmk', 'MMK'],
                    ['Mnt', 'MNT'],
                    ['Mop', 'MOP'],
                    ['Mro', 'MRO'],
                    ['Mtl', 'MTL'],
                    ['Mur', 'MUR'],
                    ['Mvr', 'MVR'],
                    ['Mwk', 'MWK'],
                    ['Mxp', 'MXP'],
                    ['Myr', 'MYR'],
                    ['Mzm', 'MZM'],
                    ['Nad', 'NAD'],
                    ['Ngn', 'NGN'],
                    ['Nio', 'NIO'],
                    ['Nlg', 'NLG'],
                    ['Nok', 'NOK'],
                    ['Npr', 'NPR'],
                    ['Nzd', 'NZD'],
                    ['Omr', 'OMR'],
                    ['Pab', 'PAB'],
                    ['Pen', 'PEN'],
                    ['Pgk', 'PGK'],
                    ['Php', 'PHP'],
                    ['Pkr', 'PKR'],
                    ['Plz', 'PLZ'],
                    ['Pte', 'PTE'],
                    ['Pyg', 'PYG'],
                    ['Qar', 'QAR'],
                    ['Rol', 'ROL'],
                    ['Rur', 'RUR'],
                    ['Rwf', 'RWF'],
                    ['Sar', 'SAR'],
                    ['Sbd', 'SBD'],
                    ['Sbl', 'SBL'],
                    ['Scr', 'SCR'],
                    ['Sdd', 'SDD'],
                    ['Sek', 'SEK'],
                    ['Sgd', 'SGD'],
                    ['Shp', 'SHP'],
                    ['Sit', 'SIT'],
                    ['Skk', 'SKK'],
                    ['Sll', 'SLL'],
                    ['Sos', 'SOS'],
                    ['Srg', 'SRG'],
                    ['Std', 'STD'],
                    ['Svc', 'SVC'],
                    ['Syp', 'SYP'],
                    ['Szl', 'SZL'],
                    ['Thb', 'THB'],
                    ['Tjr', 'TJR'],
                    ['Tmm', 'TMM'],
                    ['Tnd', 'TND'],
                    ['Top', 'TOP'],
                    ['Trl', 'TRL'],
                    ['Ttd', 'TTD'],
                    ['Twd', 'TWD'],
                    ['Tzs', 'TZS'],
                    ['Uah', 'UAH'],
                    ['Ugx', 'UGX'],
                    ['Usd', 'USD'],
                    ['Uyu', 'UYU'],
                    ['Uzs', 'UZS'],
                    ['Veb', 'VEB'],
                    ['Vnd', 'VND'],
                    ['Vuv', 'VUV'],
                    ['Wst', 'WST'],
                    ['Xaf', 'XAF'],
                    ['Xag', 'XAG'],
                    ['Xau', 'XAU'],
                    ['Xcd', 'XCD'],
                    ['Xco', 'XCO'],
                    ['Xdr', 'XDR'],
                    ['Xpd', 'XPD'],
                    ['Xpf', 'XPF'],
                    ['Xpt', 'XPT'],
                    ['Yer', 'YER'],
                    ['Yun', 'YUN'],
                    ['Zar', 'ZAR'],
                    ['Zmk', 'ZMK'],
                    ['Zwd', 'ZWD'],
                ],
            ],
        ],
    ],
];